version: '3.7'

services:
  web:
    build: .
    # command: python /code/manage.py runserver 0.0.0.0:8000
    command: gunicorn bookstore_project.wsgi -b 0.0.0.0:8000
    environment:
      - ENVIRONMENT=production
      - SECRET_KEY=8f&gt@+62rfo)s_9e%0^+l*b2947#)gr!u7i#5&3)2tb7n115f
      - DEBUG=0
      - STRIPE_TEST_PUBLISHABLE_KEY=pk_test_Gc0y9Qh50syIy8f1t4aLFrgD00DfeyrcqR
      - STRIPE_TEST_SECRET_KEY=sk_test_6a67bBMCkBOAYwZPk1bK0Z2N00DS95zJTc
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11